spring.application.name=notification-service

server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Future Kafka configuration examples. Kafka is not implemented yet.
# spring.kafka.bootstrap-servers=localhost:9092
# spring.kafka.consumer.group-id=ecommerce-group
# spring.kafka.consumer.auto-offset-reset=earliest
