spring.application.name=product-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/my_app_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=product_service
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
